### ISSUE TITLE
Option to exclude code blocks from highlighting 

### ISSUE THREAD

**Issue by aikruger** [ycnmhd/obsidian-enhanced-annotations#10]
Feature request: If I have code block with two "==" signs in it it makes the code unreadable. It would be great to have a setting to exclude code blocks

**Comment by ycnmhd** [comment]
I can't reproduce this issue. Can you share an example that contains a code block?

**Comment by meslahik** [comment]
I have a similar issue. The problem is with Live Preview mode (I see no issue with Reading mode)

When the plugin is disabled, this is the behavior:

1. When `==` is connected to text with no space, it is interpreted as highlight.
![Image](https://github.com/user-attachments/assets/090da95b-3566-4298-a891-853f0c0a0981)

2. When `==` is not connected to text, it is NOT interpreted as highlight.

![Image](https://github.com/user-attachments/assets/e30f3ef9-fe52-4984-93ff-6ae698e6f5e9)


If I enable the plugin and `==` is not connected to text, it is shown as highlight:
![Image](https://github.com/user-attachments/assets/bd3f2d93-5beb-4bd7-8e4c-4d145cb72d94)

Also, inline and normal code blocks have issue:
![Image](https://github.com/user-attachments/assets/e0897da3-a18d-4268-a967-23b151131011)

![Image](https://github.com/user-attachments/assets/ecf0bae5-ad33-4dc7-b381-c3abdf911862)

**Comment by ycnmhd** [comment]
>Also, inline and normal code blocks have issue:

Should be fixed in 0.1.9

**Comment by meslahik** [comment]
We still have issue described above after updating to 0.1.9.
This is a problem happening in Live Preview and Source modes (not in Reading mode).
Here is an screenshot:

<img width="806" height="966" alt="Image" src="https://github.com/user-attachments/assets/66526269-95ff-4306-8887-c4707e9a562a" />

**Comment by meslahik** [comment]
More examples that I encountered today:

Example one:
<img width="409" height="102" alt="Image" src="https://github.com/user-attachments/assets/f837a5c2-0166-4c6a-8e89-10f5c37749a0" />

Example two:

<img width="412" height="87" alt="Image" src="https://github.com/user-attachments/assets/2c5ab5a2-c719-403c-a269-350442b44ca4" />
