### ISSUE TITLE
Black text with highlights

### ISSUE THREAD

**Issue by tryonkus** [ycnmhd/obsidian-enhanced-annotations#14]
Currently, all highlight styles display white text on the chose background color. I'd like the ability to set the text color to black or the default color, but I don't see a way to do this.

Additionally, I'd like to be able to specify different styles for the same label of highlight and comment. For example I'd like unlabeled (Obsidian default) highlights and comments to display as follows:

- I'd like unlabeled highlights to display black text on a light shade of a chosen highlight color.
- I'd like comments to display either a dark shade of the chosen highlight color (or an entirely different color). 
- The same would be true for named labels.

To clarify, I use highlights and comments as follows: 

- Highlights are part of my text, which remind me to edit or research that section. I want them to appear as normal text with a subtle highlight background.
- Comments are not part of my text and are added notes which detail further thoughts for research, rewrite ideas, or implied section markers. I want them to appear as a readable accent color without a background in edit mode and to be hidden in reading mode.

These suggested modifications would allow comments and highlights with the same label to be related visually and optimally readable. In the current plugin, light colors are difficult to read, and dark colors interrupt the flow of text. I've tried various combinations of style settings, but the current options don't allow the visual flexibility I need.

Edit: If I add a label to highlighted text, that becomes part of the text of the Obsidian note, even in Reading view. The following added features would be very helpful:
* Hide highlight labels in Reading mode (comments are hidden completely in Reading mode already).
* Offer an option to hide labels in Editing mode and only display them when the cursor is in the comment or highlight. Labels will be easily identified by the style of the text.
* Offer an option to strip comments and highlights for final output. As an alternative, it may be possible to do this via a regex command in Linter.

Thanks for your consideration.

Ken Tryon

**Comment by tryonkus** [comment]
I just realized why you create highlights with white text–in all your example GIFs, you are working in dark mode, hence with white text. I work almost exclusively in light mode and prefer dark text. Perhaps my feature request should be simply to keep text consistent with the current mode or to allow different styling for light and dark modes.

**Comment by ycnmhd** [comment]
> Perhaps my feature request should be simply to keep text consistent with the current mode

The plugin was applying white color regardless of the current mode. This oversight is fixed in version 0.1.5.

**Comment by tryonkus** [comment]
Thanks!

**Comment by tryonkus** [comment]
That fixed it--appreciated. My highlights are readable again.

There is still an issue that if I make the default (no label) light, it works well as a highlight background but not as a comment text color. I can choose a color around 50% lightness, and that works relatively well for both, but I'd prefer to use a lighter color. Without the plugin, the highlight and comment colors are different—would it be possible to replicate this in the plugin? (basically my original request)

**Comment by ycnmhd** [comment]
The ability to style the same label differently based on the annotation type (comment or highlight) has been added in 0.1.6

> Offer an option to hide labels in Editing mode and only display them when the cursor is in the comment or highlight. Labels will be easily identified by the style of the text

This feature will be added sometime in the future

**Comment by tryonkus** [comment]
Thank you for being so responsive—that works great. Hiding labels would be nice but it is not pressing—I'm just imagining what could be helpful.

I have been using Obsidian for note taking since last year, and I recently moved from Ulysses to Obsidian for my writing. I've been figuring out how to recreate Ulysses features that I used frequently, and your plugin has been very helpful in creating notes on my writing for ideas or areas that need to be rewritten or researched further.

kt
